### ISSUE TITLE
802.1q mode is wrong 

### ISSUE THREAD

**Issue by gerardocastaldo** [nautobot/nautobot-plugin-ssot-arista-cloudvision#139]
### Environment
* Python version:  3.9.16
* Nautobot version:  v1.5.9
* aristacv-sync version:  1.5.0

### Expected Behavior
The interfaces in switchport trunk mode are recognized and configured in mode "TAGGED"

### Observed Behavior
The interfaces in switchport trunk mode aren't recognized and configured in mode "ACCESS"

Hi, I think that it isn't a bug of the plugin because the CVaaS don't report the correct mode of the switchport interfaces. 

I have a propose, if the CVaaS output is wrong is better to don't configure it in Nautobot. 
### Steps to Reproduce
1.   To reproduce the question do you need to have a interface configured in switch trunk .
2.   Syncing CVaaS or CVP to nautobot
3.   Verify the configured interface in Nautobot.

**Comment by jdrew82** [comment]
Just to be clear, are you saying that CVP itself is saying that the interfaces are access when they should be trunks? If you're saying that we should ignore that error, we would need some way to identify it is indeed an error and handle accordingly.

**Comment by gerardocastaldo** [comment]
Hi, I'll try to explain myself better.
Cloudvision correctly identifies the operating mode of a switch port by indicating whether it is routed or bridged.

however, bridged ports can be access or trunk. Cloudvision does not indicate this status and does not report any parameters indicating the vlans allocated.

This is certainly true when looking at the state of an interface. I don't know if you can validate it by looking at other metrics.

Explained this I think it is better to avoid populating the access mode information in nautobot as it would overwrite any information that a user would enter manually.

Best regards
Gerry

**Comment by jdrew82** [comment]
I think I get ya now. I'll have to look at the responses again from my test environment. Currently the mode is being determined by the `get_interface_mode` method in the Cloudvision util functions. It's currently looking at the `["switchportMode"]["Name"]` update to determine the mode.

**Comment by gerardocastaldo** [comment]
Hi, i checked the interface mode on CVaaS dashboard. I don't understand if in your lab it works.
In my environment i have ports in switchport access, switchport trunk and routed but the final configuration is always access.

**Comment by gerardocastaldo** [comment]
I use the CVaaS. I attached the pngs for study cases with the switch configuration.

I doesn't view if an interface is in access or trunk port.
![configuration routed port](https://user-images.githubusercontent.com/48739169/219379088-f454e432-05e8-4679-9279-5c674abab473.png)
![configuration trunk port](https://user-images.githubusercontent.com/48739169/219379090-0669327a-7e77-4ec4-8acf-4f11edef7122.png)
![configuration access port](https://user-images.githubusercontent.com/48739169/219379093-0269e42f-9da1-4a51-b8a0-482d469f718a.png)
![ACCESS PORT](https://user-images.githubusercontent.com/48739169/219379095-fb9f028e-88e4-4217-b457-0a5b974f50c5.png)
![ROUTED PORT](https://user-images.githubusercontent.com/48739169/219379098-fc1a4410-4611-41ba-8a10-6178035356c7.png)
![TRUNK PORT](https://user-images.githubusercontent.com/48739169/219379101-3d4f8cb3-d0bb-4451-9325-68b679b4fd24.png)

**Comment by gerardocastaldo** [comment]
Hi, I finally figured out how to view the information contained in the cvaas. I attached an example and you are right. 
The cvaas output is trunk but, at this point, the ssot plugin configure the nautobot ports bad.
![Immagine 2023-02-27 230605](https://user-images.githubusercontent.com/48739169/221696607-c29fbde5-f9c0-418d-8ac2-3023cbe47ad6.png)

**Comment by jdrew82** [comment]
@gerardocastaldo I'm not following. You've shown that it is in fact showing the port as a trunk in the response. Doesn't that confirm it's an issue with CVaaS if that port isn't in fact trunked?

**Comment by gerardocastaldo** [comment]
Sorry @jdrew82, I probably explained myself badly. I meant that the cvaas correctly reports the operational mode of the interfaces. If the interfaces are in "switchport mode access" it shows you "access" and if they are in "switchport mode trunk" it shows trunk.
Now it should just be understood why the output of the ssot is always access. 
![Immagine 2023-02-28 082230](https://user-images.githubusercontent.com/48739169/221783218-c6ac1660-ddf0-4645-967b-8360cf84ab53.png)

**Comment by jdrew82** [comment]
I'm not sure how that'd happen. As you can see [here](https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/blob/1c36203df3a08c1dffea24c221ae432616630993/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py#L121) if the port mode is returned as trunk the Interface mode should be set to tagged. I'd advise reviewing the output from CVaaS compared to what is loaded in the SSoT Sync Details page.

**Comment by gerardocastaldo** [comment]
Hi @jdrew82, i found the problem. 

The line [here](https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/blob/1c36203df3a08c1dffea24c221ae432616630993/nautobot_ssot_aristacv/diffsync/adapters/cloudvision.py#L102) should be changed to

            port_mode = cloudvision.get_interface_mode(client=self.conn, dId=device.serial, interface=port['interface'])

i tested it against the cvaas and it works.

I also think I found an inaccuracy. The cloudvision.get_interface_mode function returns three possible outputs.

- trunk
- access
- Unknow

I think it's a good idea to consider them. What do you think ?

**Comment by jdrew82** [comment]
@gerardocastaldo I think I see what you're meaning. I noticed I'm missing a unit test for that particular method so I'm working on a fix and a test.
