### ISSUE TITLE
Documentation for `delete_devices_on_sync(_cv_source)`

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot-plugin-ssot-arista-cloudvision#42]
### Environment
* aristacv-sync version:  1.0.1

Hello, 

the documentation (README) mentions `delete_devices_on_sync_cv_source` while the actual variable seems to be `delete_devices_on_sync`

Also, the setting `apply_import_tag` is not included in the example of `PLUGINS_CONFIG` (https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision#installation).

Best,

**Comment by qduk** [comment]
Thank you for pointing that out @u1735067.

**Comment by u1735067** [comment]
Hello, 

I don't think it's fixed?

https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/edit/develop/README.md#L138

Best,

**Comment by qduk** [comment]
@u1735067 Totally missed that one. Thank you again.
