### ISSUE TITLE
Sync from CVP fails due to multiple tag "Container"

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot-plugin-ssot-arista-cloudvision#43]
### Environment
* Python version:  3.9
* Nautobot version:  1.0.3
* aristacv-sync version:  1.0.1
* CVP: 2021.1.1

### Expected Behavior

Sync works

### Observed Behavior

Sync fails

### Steps to Reproduce
1. Create group/containers hierarchy in CVP
2. Put device in the leaf
3. Start sync

### Additional details

In CVP 2021.1.1 (at least), when you place devices in nested container, the device inherits multiple `Container` tags, which results in errors when syncing:
```
Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot_aristacv/diffsync/fromcv/cloudvision.py", line 39, in load
    self.add(self.cf)
  File "/opt/nautobot/.local/lib/python3.9/site-packages/diffsync/__init__.py", line 657, in add
    raise ObjectAlreadyExists(f"Object {uid} already present")
diffsync.exceptions.ObjectAlreadyExists: Object arista_Container__<device_name> already present
```

**Comment by qduk** [comment]
Thanks for the issue @u1735067. I'll look into this.

**Comment by qduk** [comment]
Hey @u1735067 after talking with Arista engineers, it was decided that the container tag is something we will not be syncing from CloudVision. The container tag is now skipped.
