### ISSUE TITLE
Sync interfaces when syncing devices from CloudVision to Nautobot

### ISSUE THREAD

**Issue by qduk** [nautobot/nautobot-plugin-ssot-arista-cloudvision#53]
### Environment
* Nautobot version:   1.0.1
* aristacv-sync version:   1.0.2

### Proposed Functionality
Sync device interfaces from CloudVision to Nautobot when syncing devices. 

### Use Case
Syncing of interfaces from CloudVision to Nautobot would allow Nautobot to be the SSoT of more info.

**Comment by jdrew82** [comment]
I think this can be closed now.

**Comment by qduk** [comment]
Closed by #94
