### ISSUE TITLE
sessionId 

### ISSUE THREAD

**Issue by andreas1o** [nautobot/nautobot-plugin-ssot-arista-cloudvision#54]
### Environment
* Python version:  3.6.8
* Nautobot version:  1.1.3
* aristacv-sync version:  1.0.2

Sync from cloudvision to Nautobot it looks like the configuration file dosen't match my the boolean True statment in the configuration file of nautbot
<html><body>
<div class="panel-heading"><strong>Configuration</strong></div>
                    

Parameter | Value
-- | --
Server type | On prem
CloudVision host | X
Username | nautobot
Insecure | True
Delete devices on sync | False
New device default site | cloudvision_imported
New device default role | network
New device default role color | ff0000
New device default status | cloudvision_imported
New device default status color | ff0000
Apply import tag | True

</body>
</html>
### Expected Behavior

</body>
</html>
### Observed Behavior

2021-10-01T10:32:26.788554+00:00 | Warning |   | Devices not present in Cloudvision but present in Nautobot will not be deleted from Nautobot.
-- | -- | -- | --
2021-10-01T10:32:26.788973+00:00 | Default |   | Connecting to CloudVision
2021-10-01T10:32:27.573671+00:00 | Failure |   | An exception occurred: KeyError: 'sessionId' Traceback (most recent call last):   File "/opt/nautobot/lib64/python3.6/site-packages/nautobot_ssot/jobs/base.py", line 207, in run     self.sync_data()   File "/opt/nautobot/lib64/python3.6/site-packages/nautobot_ssot_aristacv/jobs.py", line 122, in sync_data     cvutils.connect()   File "/opt/nautobot/lib64/python3.6/site-packages/nautobot_ssot_aristacv/diffsync/cvutils.py", line 40, in connect     call_creds = grpc.access_token_call_credentials(response.json()["sessionId"]) KeyError: 'sessionId'

### Steps to Reproduce
1. install nautbot standard 
2. install nautobot_ssot_aristacv with pip3 install nautobot_ssot_aristacv
3. Update he configuration file with this configuration
```
PLUGINS = ["nautobot_ssot", "nautobot_ssot_aristacv"]


PLUGINS_CONFIG = {
#   "nautobot_ssot" : {
#     ADD YOUR SETTINGS HERE
#   }
   "nautobot_ssot_aristacv": {
#     "cvaas_token": "",
     "cvp_host": "X",
     "cvp_user": "nautobot",
     "cvp_password": "X",
     "insecure": "True",
#     "from_cloudvision_default_site": "",
#     "from_cloudvision_default_device_role": "",
#     "from_cloudvision_default_device_role_color": "",
#     "from_cloudvision_default_device_status": "",
#     "from_cloudvision_default_device_status_color": "",
#     "delete_devices_on_sync": "",
     "apply_import_tag": "True"
   }
 }
```

**Comment by chipn** [comment]
I suspect the authentication is failing. Is there any chance you could have the wrong username/password configured?  If that isn't the case, we'd need more information on the response from CVP.

I apparently missed putting in error handling for failed authentication, so we'll get that added.

**Comment by andreas1o** [comment]
There is no log in the CVP of me even trying to access ( at least not in the auth log for this particular user)
I can login with the credentials in the normal webui.

**Comment by qduk** [comment]
@andreas1o We had a PR that updated the error message. Can you provide the cloudvision version you are connecting to?

**Comment by jdrew82** [comment]
I believe this is due to how the variable is read in from the settings. Without using the `is_truthy` function from Nautobot the variable is read in as a string instead of a boolean. Adding the function wrapper around the variable fixes this.

**Comment by qduk** [comment]
Closing as the issue should be fixed and haven't heard from the end user.
