### ISSUE TITLE
Associating new roles with Device Role in Nautobot

### ISSUE THREAD

**Issue by pibjndata** [nautobot/nautobot-plugin-ssot-arista-cloudvision#60]
### Environment
* Nautobot version:  1.1.3
* aristacv-sync version:  1.0.2

### Proposed Functionality

Is there a possibility to increase amount of roles, as far as I saw in Custom fields, there are supported only “Leafs” or “spines”, we have much more in Arista:
leafs, subleafs, spines, super-spines, borders, route_servers. Is there a possibility to have it also in plugin.

What is more, the role could be associated to Device Role in Nautobot automatically

**Comment by jdrew82** [comment]
@pibjndata There is another request #51 that is asking for similar. Unfortunately, I believe the only options for allowing customization of Device Role would be to have it look for a User Tag that has "Role" as a key or does some hostname scrapping to possibly match some identifier there for a list of roles. Would either of these options work for your needs?

**Comment by qduk** [comment]
Closing this per #108.
