### ISSUE TITLE
Integration with Device Lifecycle Plugin

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-plugin-ssot-arista-cloudvision#87]
### Environment
* Nautobot version:  1.4.1
* aristacv-sync version:  1.2.1

### Proposed Functionality
It'd be nice to have the Software Version of a Device be noted in the Device Lifecycle plugin if it's also imported. 

### Use Case

Instead of having EOS Version noted as a Custom Field it'd be much better to have those versions created in the DLC plugin and a Relationship created. This enables far more functionality with this information, such as defining Validated Software or CVEs.

**Comment by KalleDK** [comment]
Hahaha - came just for that to see how easy/hard it would be
