### ISSUE TITLE
Use filter instead of test in loop

### ISSUE THREAD

**Issue by KalleDK** [nautobot/nautobot-plugin-ssot-arista-cloudvision#93]
Wouldn't it be better to apply the arista as a filter, that way you don't have to load all the devices?

https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/blob/1429eb5be00f8dca9627d279212c40a08eaff9cb/nautobot_ssot_aristacv/diffsync/adapters/nautobot.py#L23-L26

**Comment by jdrew82** [comment]
Agreed 100%. I've integrated a fix for this into my PR for DLC integration.

**Comment by qduk** [comment]
Closed per #101
