### ISSUE TITLE
Customfield Sync-failure

### ISSUE THREAD

**Issue by soeren-n** [nautobot/nautobot-plugin-ssot-arista-cloudvision#95]
### Environment
* Python version:  3.8.12
* Nautobot version:  1.4.3
* aristacv-sync version:  1.2.0 

When syncing data from CVP to Nautobot, plugin fails when "Loading data from Nautobot".
The plugin apparently try to validate all custom fields, not just "it's own" or the ones created/handled by the plugin.
The plugin should only care about it's own fields.

The example happens because the fieldvalidation is done for all custom fields.

```
An exception occurred: ValidationError: 1 validation error for CustomField value str type expected (type=type_error.str)

Traceback (most recent call last):
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 327, in run
    self.sync_data()
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot_aristacv/jobs.py", line 131, in sync_data
    nb.load()
  File "/opt/nautobot/lib64/python3.8/site-packages/nautobot_ssot_aristacv/diffsync/fromcv/nautobot.py", line 34, in load
    self.cf = CustomField(name=cf_name, value=cf_value, device_name=dev.name)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CustomField
value
  str type expected (type=type_error.str)__

```

**Comment by jdrew82** [comment]
I believe the issue at play here is that the base model for CustomField assumes that the value will always be a string. This isn't necessarily the case as a CustomField could be an integer, or a boolean, etc. I think we should probably look at a better way of importing User Tags into custom fields.

**Comment by jdrew82** [comment]
@soeren-n Can you confirm this has been fixed?
